/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AutomotiveRouteImport } from './routes/automotive'
import { Route as BookanappointmentRouteImport } from './routes/bookanappointment'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FloridaLocationRouteImport } from './routes/florida-location'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IslandiaLocationRouteImport } from './routes/islandia-location'
import { Route as LegalProfessionalsRouteImport } from './routes/legal-professionals'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as NewYorkCityLocationRouteImport } from './routes/new-york-city-location'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as PrivacyPolicy2RouteImport } from './routes/privacy-policy-2'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ApiChatbaseLeadRouteImport } from './routes/api/chatbase-lead'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CmsIndexRouteImport } from './routes/cms/index'
import { Route as CmsNewRouteImport } from './routes/cms/new'
import { Route as InternalRedirectsRouteImport } from './routes/internal/redirects'
import { Route as InternalSettingsRouteImport } from './routes/internal/settings'
import { Route as InternalWebinarLinksRouteImport } from './routes/internal/webinar-links'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsBookkeepingRouteImport } from './routes/solutions/bookkeeping'
import { Route as SolutionsCfoAdvisoryServicesRouteImport } from './routes/solutions/cfo-advisory-services'
import { Route as SolutionsTaxRouteImport } from './routes/solutions/tax'
import { Route as SolutionsWealthManagementRouteImport } from './routes/solutions/wealth-management'
import { Route as ToolsEventsRouteImport } from './routes/tools/events'
import { Route as ToolsLinksRouteImport } from './routes/tools/links'
import { Route as ToolsRedirectionsRouteImport } from './routes/tools/redirections'
import { Route as CmsIdEditRouteImport } from './routes/cms/$id/edit'
import { Route as CmsIdPreviewRouteImport } from './routes/cms/$id/preview'
import { Route as InternalPagesIndexRouteImport } from './routes/internal/pages/index'
import { Route as InternalPagesNewRouteImport } from './routes/internal/pages/new'
import { Route as InternalPagesIdEditRouteImport } from './routes/internal/pages/$id/edit'
import { Route as InternalPagesIdPreviewRouteImport } from './routes/internal/pages/$id/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotiveRoute = AutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const BookanappointmentRoute = BookanappointmentRouteImport.update({
  id: '/bookanappointment',
  path: '/bookanappointment',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FloridaLocationRoute = FloridaLocationRouteImport.update({
  id: '/florida-location',
  path: '/florida-location',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandiaLocationRoute = IslandiaLocationRouteImport.update({
  id: '/islandia-location',
  path: '/islandia-location',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalProfessionalsRoute = LegalProfessionalsRouteImport.update({
  id: '/legal-professionals',
  path: '/legal-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewYorkCityLocationRoute = NewYorkCityLocationRouteImport.update({
  id: '/new-york-city-location',
  path: '/new-york-city-location',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicy2Route = PrivacyPolicy2RouteImport.update({
  id: '/privacy-policy-2',
  path: '/privacy-policy-2',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatbaseLeadRoute = ApiChatbaseLeadRouteImport.update({
  id: '/api/chatbase-lead',
  path: '/api/chatbase-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIndexRoute = CmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsNewRoute = CmsNewRouteImport.update({
  id: '/cms/new',
  path: '/cms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalRedirectsRoute = InternalRedirectsRouteImport.update({
  id: '/internal/redirects',
  path: '/internal/redirects',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSettingsRoute = InternalSettingsRouteImport.update({
  id: '/internal/settings',
  path: '/internal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalWebinarLinksRoute = InternalWebinarLinksRouteImport.update({
  id: '/internal/webinar-links',
  path: '/internal/webinar-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBookkeepingRoute = SolutionsBookkeepingRouteImport.update({
  id: '/solutions/bookkeeping',
  path: '/solutions/bookkeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCfoAdvisoryServicesRoute =
  SolutionsCfoAdvisoryServicesRouteImport.update({
    id: '/solutions/cfo-advisory-services',
    path: '/solutions/cfo-advisory-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsTaxRoute = SolutionsTaxRouteImport.update({
  id: '/solutions/tax',
  path: '/solutions/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWealthManagementRoute =
  SolutionsWealthManagementRouteImport.update({
    id: '/solutions/wealth-management',
    path: '/solutions/wealth-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsEventsRoute = ToolsEventsRouteImport.update({
  id: '/tools/events',
  path: '/tools/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLinksRoute = ToolsLinksRouteImport.update({
  id: '/tools/links',
  path: '/tools/links',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRedirectionsRoute = ToolsRedirectionsRouteImport.update({
  id: '/tools/redirections',
  path: '/tools/redirections',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIdEditRoute = CmsIdEditRouteImport.update({
  id: '/cms/$id/edit',
  path: '/cms/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsIdPreviewRoute = CmsIdPreviewRouteImport.update({
  id: '/cms/$id/preview',
  path: '/cms/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPagesIndexRoute = InternalPagesIndexRouteImport.update({
  id: '/internal/pages/',
  path: '/internal/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPagesNewRoute = InternalPagesNewRouteImport.update({
  id: '/internal/pages/new',
  path: '/internal/pages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPagesIdEditRoute = InternalPagesIdEditRouteImport.update({
  id: '/internal/pages/$id/edit',
  path: '/internal/pages/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalPagesIdPreviewRoute = InternalPagesIdPreviewRouteImport.update({
  id: '/internal/pages/$id/preview',
  path: '/internal/pages/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/chatbase-lead': typeof ApiChatbaseLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cms/new': typeof CmsNewRoute
  '/internal/redirects': typeof InternalRedirectsRoute
  '/internal/settings': typeof InternalSettingsRoute
  '/internal/webinar-links': typeof InternalWebinarLinksRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/tools/events': typeof ToolsEventsRoute
  '/tools/links': typeof ToolsLinksRoute
  '/tools/redirections': typeof ToolsRedirectionsRoute
  '/blog/': typeof BlogIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/cms/$id/edit': typeof CmsIdEditRoute
  '/cms/$id/preview': typeof CmsIdPreviewRoute
  '/internal/pages/new': typeof InternalPagesNewRoute
  '/internal/pages/': typeof InternalPagesIndexRoute
  '/internal/pages/$id/edit': typeof InternalPagesIdEditRoute
  '/internal/pages/$id/preview': typeof InternalPagesIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/chatbase-lead': typeof ApiChatbaseLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cms/new': typeof CmsNewRoute
  '/internal/redirects': typeof InternalRedirectsRoute
  '/internal/settings': typeof InternalSettingsRoute
  '/internal/webinar-links': typeof InternalWebinarLinksRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/tools/events': typeof ToolsEventsRoute
  '/tools/links': typeof ToolsLinksRoute
  '/tools/redirections': typeof ToolsRedirectionsRoute
  '/blog': typeof BlogIndexRoute
  '/cms': typeof CmsIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/cms/$id/edit': typeof CmsIdEditRoute
  '/cms/$id/preview': typeof CmsIdPreviewRoute
  '/internal/pages/new': typeof InternalPagesNewRoute
  '/internal/pages': typeof InternalPagesIndexRoute
  '/internal/pages/$id/edit': typeof InternalPagesIdEditRoute
  '/internal/pages/$id/preview': typeof InternalPagesIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/chatbase-lead': typeof ApiChatbaseLeadRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cms/new': typeof CmsNewRoute
  '/internal/redirects': typeof InternalRedirectsRoute
  '/internal/settings': typeof InternalSettingsRoute
  '/internal/webinar-links': typeof InternalWebinarLinksRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/tools/events': typeof ToolsEventsRoute
  '/tools/links': typeof ToolsLinksRoute
  '/tools/redirections': typeof ToolsRedirectionsRoute
  '/blog/': typeof BlogIndexRoute
  '/cms/': typeof CmsIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/cms/$id/edit': typeof CmsIdEditRoute
  '/cms/$id/preview': typeof CmsIdPreviewRoute
  '/internal/pages/new': typeof InternalPagesNewRoute
  '/internal/pages/': typeof InternalPagesIndexRoute
  '/internal/pages/$id/edit': typeof InternalPagesIdEditRoute
  '/internal/pages/$id/preview': typeof InternalPagesIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/events'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/api/chatbase-lead'
    | '/blog/$slug'
    | '/cms/new'
    | '/internal/redirects'
    | '/internal/settings'
    | '/internal/webinar-links'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/tools/events'
    | '/tools/links'
    | '/tools/redirections'
    | '/blog/'
    | '/cms/'
    | '/solutions/'
    | '/cms/$id/edit'
    | '/cms/$id/preview'
    | '/internal/pages/new'
    | '/internal/pages/'
    | '/internal/pages/$id/edit'
    | '/internal/pages/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/events'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/api/chatbase-lead'
    | '/blog/$slug'
    | '/cms/new'
    | '/internal/redirects'
    | '/internal/settings'
    | '/internal/webinar-links'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/tools/events'
    | '/tools/links'
    | '/tools/redirections'
    | '/blog'
    | '/cms'
    | '/solutions'
    | '/cms/$id/edit'
    | '/cms/$id/preview'
    | '/internal/pages/new'
    | '/internal/pages'
    | '/internal/pages/$id/edit'
    | '/internal/pages/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/events'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/api/chatbase-lead'
    | '/blog/$slug'
    | '/cms/new'
    | '/internal/redirects'
    | '/internal/settings'
    | '/internal/webinar-links'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/tools/events'
    | '/tools/links'
    | '/tools/redirections'
    | '/blog/'
    | '/cms/'
    | '/solutions/'
    | '/cms/$id/edit'
    | '/cms/$id/preview'
    | '/internal/pages/new'
    | '/internal/pages/'
    | '/internal/pages/$id/edit'
    | '/internal/pages/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AutomotiveRoute: typeof AutomotiveRoute
  BookanappointmentRoute: typeof BookanappointmentRoute
  CareersRoute: typeof CareersRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FloridaLocationRoute: typeof FloridaLocationRoute
  HealthcareRoute: typeof HealthcareRoute
  HospitalityRoute: typeof HospitalityRoute
  IndustriesRoute: typeof IndustriesRoute
  IslandiaLocationRoute: typeof IslandiaLocationRoute
  LegalProfessionalsRoute: typeof LegalProfessionalsRoute
  ManufacturersRoute: typeof ManufacturersRoute
  NewYorkCityLocationRoute: typeof NewYorkCityLocationRoute
  OurTeamRoute: typeof OurTeamRoute
  PrivacyPolicy2Route: typeof PrivacyPolicy2Route
  RealEstateRoute: typeof RealEstateRoute
  ResourcesRoute: typeof ResourcesRoute
  RetailRoute: typeof RetailRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiChatbaseLeadRoute: typeof ApiChatbaseLeadRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CmsNewRoute: typeof CmsNewRoute
  InternalRedirectsRoute: typeof InternalRedirectsRoute
  InternalSettingsRoute: typeof InternalSettingsRoute
  InternalWebinarLinksRoute: typeof InternalWebinarLinksRoute
  SolutionsBookkeepingRoute: typeof SolutionsBookkeepingRoute
  SolutionsCfoAdvisoryServicesRoute: typeof SolutionsCfoAdvisoryServicesRoute
  SolutionsTaxRoute: typeof SolutionsTaxRoute
  SolutionsWealthManagementRoute: typeof SolutionsWealthManagementRoute
  ToolsEventsRoute: typeof ToolsEventsRoute
  ToolsLinksRoute: typeof ToolsLinksRoute
  ToolsRedirectionsRoute: typeof ToolsRedirectionsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CmsIndexRoute: typeof CmsIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  CmsIdEditRoute: typeof CmsIdEditRoute
  CmsIdPreviewRoute: typeof CmsIdPreviewRoute
  InternalPagesNewRoute: typeof InternalPagesNewRoute
  InternalPagesIndexRoute: typeof InternalPagesIndexRoute
  InternalPagesIdEditRoute: typeof InternalPagesIdEditRoute
  InternalPagesIdPreviewRoute: typeof InternalPagesIdPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotive': {
      id: '/automotive'
      path: '/automotive'
      fullPath: '/automotive'
      preLoaderRoute: typeof AutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookanappointment': {
      id: '/bookanappointment'
      path: '/bookanappointment'
      fullPath: '/bookanappointment'
      preLoaderRoute: typeof BookanappointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florida-location': {
      id: '/florida-location'
      path: '/florida-location'
      fullPath: '/florida-location'
      preLoaderRoute: typeof FloridaLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islandia-location': {
      id: '/islandia-location'
      path: '/islandia-location'
      fullPath: '/islandia-location'
      preLoaderRoute: typeof IslandiaLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-professionals': {
      id: '/legal-professionals'
      path: '/legal-professionals'
      fullPath: '/legal-professionals'
      preLoaderRoute: typeof LegalProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-york-city-location': {
      id: '/new-york-city-location'
      path: '/new-york-city-location'
      fullPath: '/new-york-city-location'
      preLoaderRoute: typeof NewYorkCityLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy-2': {
      id: '/privacy-policy-2'
      path: '/privacy-policy-2'
      fullPath: '/privacy-policy-2'
      preLoaderRoute: typeof PrivacyPolicy2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chatbase-lead': {
      id: '/api/chatbase-lead'
      path: '/api/chatbase-lead'
      fullPath: '/api/chatbase-lead'
      preLoaderRoute: typeof ApiChatbaseLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/': {
      id: '/cms/'
      path: '/cms'
      fullPath: '/cms/'
      preLoaderRoute: typeof CmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/new': {
      id: '/cms/new'
      path: '/cms/new'
      fullPath: '/cms/new'
      preLoaderRoute: typeof CmsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/redirects': {
      id: '/internal/redirects'
      path: '/internal/redirects'
      fullPath: '/internal/redirects'
      preLoaderRoute: typeof InternalRedirectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/settings': {
      id: '/internal/settings'
      path: '/internal/settings'
      fullPath: '/internal/settings'
      preLoaderRoute: typeof InternalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/webinar-links': {
      id: '/internal/webinar-links'
      path: '/internal/webinar-links'
      fullPath: '/internal/webinar-links'
      preLoaderRoute: typeof InternalWebinarLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/bookkeeping': {
      id: '/solutions/bookkeeping'
      path: '/solutions/bookkeeping'
      fullPath: '/solutions/bookkeeping'
      preLoaderRoute: typeof SolutionsBookkeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cfo-advisory-services': {
      id: '/solutions/cfo-advisory-services'
      path: '/solutions/cfo-advisory-services'
      fullPath: '/solutions/cfo-advisory-services'
      preLoaderRoute: typeof SolutionsCfoAdvisoryServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/tax': {
      id: '/solutions/tax'
      path: '/solutions/tax'
      fullPath: '/solutions/tax'
      preLoaderRoute: typeof SolutionsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/wealth-management': {
      id: '/solutions/wealth-management'
      path: '/solutions/wealth-management'
      fullPath: '/solutions/wealth-management'
      preLoaderRoute: typeof SolutionsWealthManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/events': {
      id: '/tools/events'
      path: '/tools/events'
      fullPath: '/tools/events'
      preLoaderRoute: typeof ToolsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/links': {
      id: '/tools/links'
      path: '/tools/links'
      fullPath: '/tools/links'
      preLoaderRoute: typeof ToolsLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/redirections': {
      id: '/tools/redirections'
      path: '/tools/redirections'
      fullPath: '/tools/redirections'
      preLoaderRoute: typeof ToolsRedirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/$id/edit': {
      id: '/cms/$id/edit'
      path: '/cms/$id/edit'
      fullPath: '/cms/$id/edit'
      preLoaderRoute: typeof CmsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms/$id/preview': {
      id: '/cms/$id/preview'
      path: '/cms/$id/preview'
      fullPath: '/cms/$id/preview'
      preLoaderRoute: typeof CmsIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/pages/': {
      id: '/internal/pages/'
      path: '/internal/pages'
      fullPath: '/internal/pages/'
      preLoaderRoute: typeof InternalPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/pages/new': {
      id: '/internal/pages/new'
      path: '/internal/pages/new'
      fullPath: '/internal/pages/new'
      preLoaderRoute: typeof InternalPagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/pages/$id/edit': {
      id: '/internal/pages/$id/edit'
      path: '/internal/pages/$id/edit'
      fullPath: '/internal/pages/$id/edit'
      preLoaderRoute: typeof InternalPagesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/pages/$id/preview': {
      id: '/internal/pages/$id/preview'
      path: '/internal/pages/$id/preview'
      fullPath: '/internal/pages/$id/preview'
      preLoaderRoute: typeof InternalPagesIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AutomotiveRoute: AutomotiveRoute,
  BookanappointmentRoute: BookanappointmentRoute,
  CareersRoute: CareersRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FloridaLocationRoute: FloridaLocationRoute,
  HealthcareRoute: HealthcareRoute,
  HospitalityRoute: HospitalityRoute,
  IndustriesRoute: IndustriesRoute,
  IslandiaLocationRoute: IslandiaLocationRoute,
  LegalProfessionalsRoute: LegalProfessionalsRoute,
  ManufacturersRoute: ManufacturersRoute,
  NewYorkCityLocationRoute: NewYorkCityLocationRoute,
  OurTeamRoute: OurTeamRoute,
  PrivacyPolicy2Route: PrivacyPolicy2Route,
  RealEstateRoute: RealEstateRoute,
  ResourcesRoute: ResourcesRoute,
  RetailRoute: RetailRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiChatbaseLeadRoute: ApiChatbaseLeadRoute,
  BlogSlugRoute: BlogSlugRoute,
  CmsNewRoute: CmsNewRoute,
  InternalRedirectsRoute: InternalRedirectsRoute,
  InternalSettingsRoute: InternalSettingsRoute,
  InternalWebinarLinksRoute: InternalWebinarLinksRoute,
  SolutionsBookkeepingRoute: SolutionsBookkeepingRoute,
  SolutionsCfoAdvisoryServicesRoute: SolutionsCfoAdvisoryServicesRoute,
  SolutionsTaxRoute: SolutionsTaxRoute,
  SolutionsWealthManagementRoute: SolutionsWealthManagementRoute,
  ToolsEventsRoute: ToolsEventsRoute,
  ToolsLinksRoute: ToolsLinksRoute,
  ToolsRedirectionsRoute: ToolsRedirectionsRoute,
  BlogIndexRoute: BlogIndexRoute,
  CmsIndexRoute: CmsIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  CmsIdEditRoute: CmsIdEditRoute,
  CmsIdPreviewRoute: CmsIdPreviewRoute,
  InternalPagesNewRoute: InternalPagesNewRoute,
  InternalPagesIndexRoute: InternalPagesIndexRoute,
  InternalPagesIdEditRoute: InternalPagesIdEditRoute,
  InternalPagesIdPreviewRoute: InternalPagesIdPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
