/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AutomotiveRouteImport } from './routes/automotive'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IslandiaLocationRouteImport } from './routes/islandia-location'
import { Route as LegalProfessionalsRouteImport } from './routes/legal-professionals'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as NewYorkCityLocationRouteImport } from './routes/new-york-city-location'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TierraVerdeFlRouteImport } from './routes/tierra-verde-fl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotiveRoute = AutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandiaLocationRoute = IslandiaLocationRouteImport.update({
  id: '/islandia-location',
  path: '/islandia-location',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalProfessionalsRoute = LegalProfessionalsRouteImport.update({
  id: '/legal-professionals',
  path: '/legal-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewYorkCityLocationRoute = NewYorkCityLocationRouteImport.update({
  id: '/new-york-city-location',
  path: '/new-york-city-location',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TierraVerdeFlRoute = TierraVerdeFlRouteImport.update({
  id: '/tierra-verde-fl',
  path: '/tierra-verde-fl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/solutions': typeof SolutionsRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/automotive'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/solutions'
    | '/testimonials'
    | '/tierra-verde-fl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/automotive'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/solutions'
    | '/testimonials'
    | '/tierra-verde-fl'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/automotive'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/solutions'
    | '/testimonials'
    | '/tierra-verde-fl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AutomotiveRoute: typeof AutomotiveRoute
  CareersRoute: typeof CareersRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  HealthcareRoute: typeof HealthcareRoute
  HospitalityRoute: typeof HospitalityRoute
  IndustriesRoute: typeof IndustriesRoute
  IslandiaLocationRoute: typeof IslandiaLocationRoute
  LegalProfessionalsRoute: typeof LegalProfessionalsRoute
  ManufacturersRoute: typeof ManufacturersRoute
  NewYorkCityLocationRoute: typeof NewYorkCityLocationRoute
  OurTeamRoute: typeof OurTeamRoute
  RealEstateRoute: typeof RealEstateRoute
  ResourcesRoute: typeof ResourcesRoute
  RetailRoute: typeof RetailRoute
  SolutionsRoute: typeof SolutionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TierraVerdeFlRoute: typeof TierraVerdeFlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotive': {
      id: '/automotive'
      path: '/automotive'
      fullPath: '/automotive'
      preLoaderRoute: typeof AutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islandia-location': {
      id: '/islandia-location'
      path: '/islandia-location'
      fullPath: '/islandia-location'
      preLoaderRoute: typeof IslandiaLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-professionals': {
      id: '/legal-professionals'
      path: '/legal-professionals'
      fullPath: '/legal-professionals'
      preLoaderRoute: typeof LegalProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-york-city-location': {
      id: '/new-york-city-location'
      path: '/new-york-city-location'
      fullPath: '/new-york-city-location'
      preLoaderRoute: typeof NewYorkCityLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierra-verde-fl': {
      id: '/tierra-verde-fl'
      path: '/tierra-verde-fl'
      fullPath: '/tierra-verde-fl'
      preLoaderRoute: typeof TierraVerdeFlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AutomotiveRoute: AutomotiveRoute,
  CareersRoute: CareersRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  HealthcareRoute: HealthcareRoute,
  HospitalityRoute: HospitalityRoute,
  IndustriesRoute: IndustriesRoute,
  IslandiaLocationRoute: IslandiaLocationRoute,
  LegalProfessionalsRoute: LegalProfessionalsRoute,
  ManufacturersRoute: ManufacturersRoute,
  NewYorkCityLocationRoute: NewYorkCityLocationRoute,
  OurTeamRoute: OurTeamRoute,
  RealEstateRoute: RealEstateRoute,
  ResourcesRoute: ResourcesRoute,
  RetailRoute: RetailRoute,
  SolutionsRoute: SolutionsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TierraVerdeFlRoute: TierraVerdeFlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
