/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AutomotiveRouteImport } from './routes/automotive'
import { Route as BookanappointmentRouteImport } from './routes/bookanappointment'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as FloridaLocationRouteImport } from './routes/florida-location'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IslandiaLocationRouteImport } from './routes/islandia-location'
import { Route as LegalProfessionalsRouteImport } from './routes/legal-professionals'
import { Route as ManufacturersRouteImport } from './routes/manufacturers'
import { Route as NewYorkCityLocationRouteImport } from './routes/new-york-city-location'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as PrivacyPolicy2RouteImport } from './routes/privacy-policy-2'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TierraVerdeFlRouteImport } from './routes/tierra-verde-fl'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsBookkeepingRouteImport } from './routes/solutions/bookkeeping'
import { Route as SolutionsCfoAdvisoryServicesRouteImport } from './routes/solutions/cfo-advisory-services'
import { Route as SolutionsTaxRouteImport } from './routes/solutions/tax'
import { Route as SolutionsWealthManagementRouteImport } from './routes/solutions/wealth-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotiveRoute = AutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const BookanappointmentRoute = BookanappointmentRouteImport.update({
  id: '/bookanappointment',
  path: '/bookanappointment',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const FloridaLocationRoute = FloridaLocationRouteImport.update({
  id: '/florida-location',
  path: '/florida-location',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandiaLocationRoute = IslandiaLocationRouteImport.update({
  id: '/islandia-location',
  path: '/islandia-location',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalProfessionalsRoute = LegalProfessionalsRouteImport.update({
  id: '/legal-professionals',
  path: '/legal-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturersRoute = ManufacturersRouteImport.update({
  id: '/manufacturers',
  path: '/manufacturers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewYorkCityLocationRoute = NewYorkCityLocationRouteImport.update({
  id: '/new-york-city-location',
  path: '/new-york-city-location',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicy2Route = PrivacyPolicy2RouteImport.update({
  id: '/privacy-policy-2',
  path: '/privacy-policy-2',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TierraVerdeFlRoute = TierraVerdeFlRouteImport.update({
  id: '/tierra-verde-fl',
  path: '/tierra-verde-fl',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsBookkeepingRoute = SolutionsBookkeepingRouteImport.update({
  id: '/solutions/bookkeeping',
  path: '/solutions/bookkeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCfoAdvisoryServicesRoute =
  SolutionsCfoAdvisoryServicesRouteImport.update({
    id: '/solutions/cfo-advisory-services',
    path: '/solutions/cfo-advisory-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsTaxRoute = SolutionsTaxRouteImport.update({
  id: '/solutions/tax',
  path: '/solutions/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWealthManagementRoute =
  SolutionsWealthManagementRouteImport.update({
    id: '/solutions/wealth-management',
    path: '/solutions/wealth-management',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/automotive': typeof AutomotiveRoute
  '/bookanappointment': typeof BookanappointmentRoute
  '/careers': typeof CareersRoute
  '/construction': typeof ConstructionRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/florida-location': typeof FloridaLocationRoute
  '/healthcare': typeof HealthcareRoute
  '/hospitality': typeof HospitalityRoute
  '/industries': typeof IndustriesRoute
  '/islandia-location': typeof IslandiaLocationRoute
  '/legal-professionals': typeof LegalProfessionalsRoute
  '/manufacturers': typeof ManufacturersRoute
  '/new-york-city-location': typeof NewYorkCityLocationRoute
  '/our-team': typeof OurTeamRoute
  '/privacy-policy-2': typeof PrivacyPolicy2Route
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/retail': typeof RetailRoute
  '/testimonials': typeof TestimonialsRoute
  '/tierra-verde-fl': typeof TierraVerdeFlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/solutions/bookkeeping': typeof SolutionsBookkeepingRoute
  '/solutions/cfo-advisory-services': typeof SolutionsCfoAdvisoryServicesRoute
  '/solutions/tax': typeof SolutionsTaxRoute
  '/solutions/wealth-management': typeof SolutionsWealthManagementRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/contact-us'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/tierra-verde-fl'
    | '/blog/$slug'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/blog/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/contact-us'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/tierra-verde-fl'
    | '/blog/$slug'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/blog'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about-us'
    | '/automotive'
    | '/bookanappointment'
    | '/careers'
    | '/construction'
    | '/contact'
    | '/contact-us'
    | '/florida-location'
    | '/healthcare'
    | '/hospitality'
    | '/industries'
    | '/islandia-location'
    | '/legal-professionals'
    | '/manufacturers'
    | '/new-york-city-location'
    | '/our-team'
    | '/privacy-policy-2'
    | '/real-estate'
    | '/resources'
    | '/retail'
    | '/testimonials'
    | '/tierra-verde-fl'
    | '/blog/$slug'
    | '/solutions/bookkeeping'
    | '/solutions/cfo-advisory-services'
    | '/solutions/tax'
    | '/solutions/wealth-management'
    | '/blog/'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AutomotiveRoute: typeof AutomotiveRoute
  BookanappointmentRoute: typeof BookanappointmentRoute
  CareersRoute: typeof CareersRoute
  ConstructionRoute: typeof ConstructionRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  FloridaLocationRoute: typeof FloridaLocationRoute
  HealthcareRoute: typeof HealthcareRoute
  HospitalityRoute: typeof HospitalityRoute
  IndustriesRoute: typeof IndustriesRoute
  IslandiaLocationRoute: typeof IslandiaLocationRoute
  LegalProfessionalsRoute: typeof LegalProfessionalsRoute
  ManufacturersRoute: typeof ManufacturersRoute
  NewYorkCityLocationRoute: typeof NewYorkCityLocationRoute
  OurTeamRoute: typeof OurTeamRoute
  PrivacyPolicy2Route: typeof PrivacyPolicy2Route
  RealEstateRoute: typeof RealEstateRoute
  ResourcesRoute: typeof ResourcesRoute
  RetailRoute: typeof RetailRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TierraVerdeFlRoute: typeof TierraVerdeFlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SolutionsBookkeepingRoute: typeof SolutionsBookkeepingRoute
  SolutionsCfoAdvisoryServicesRoute: typeof SolutionsCfoAdvisoryServicesRoute
  SolutionsTaxRoute: typeof SolutionsTaxRoute
  SolutionsWealthManagementRoute: typeof SolutionsWealthManagementRoute
  BlogIndexRoute: typeof BlogIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotive': {
      id: '/automotive'
      path: '/automotive'
      fullPath: '/automotive'
      preLoaderRoute: typeof AutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookanappointment': {
      id: '/bookanappointment'
      path: '/bookanappointment'
      fullPath: '/bookanappointment'
      preLoaderRoute: typeof BookanappointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florida-location': {
      id: '/florida-location'
      path: '/florida-location'
      fullPath: '/florida-location'
      preLoaderRoute: typeof FloridaLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islandia-location': {
      id: '/islandia-location'
      path: '/islandia-location'
      fullPath: '/islandia-location'
      preLoaderRoute: typeof IslandiaLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-professionals': {
      id: '/legal-professionals'
      path: '/legal-professionals'
      fullPath: '/legal-professionals'
      preLoaderRoute: typeof LegalProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturers': {
      id: '/manufacturers'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof ManufacturersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-york-city-location': {
      id: '/new-york-city-location'
      path: '/new-york-city-location'
      fullPath: '/new-york-city-location'
      preLoaderRoute: typeof NewYorkCityLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy-2': {
      id: '/privacy-policy-2'
      path: '/privacy-policy-2'
      fullPath: '/privacy-policy-2'
      preLoaderRoute: typeof PrivacyPolicy2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tierra-verde-fl': {
      id: '/tierra-verde-fl'
      path: '/tierra-verde-fl'
      fullPath: '/tierra-verde-fl'
      preLoaderRoute: typeof TierraVerdeFlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/bookkeeping': {
      id: '/solutions/bookkeeping'
      path: '/solutions/bookkeeping'
      fullPath: '/solutions/bookkeeping'
      preLoaderRoute: typeof SolutionsBookkeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cfo-advisory-services': {
      id: '/solutions/cfo-advisory-services'
      path: '/solutions/cfo-advisory-services'
      fullPath: '/solutions/cfo-advisory-services'
      preLoaderRoute: typeof SolutionsCfoAdvisoryServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/tax': {
      id: '/solutions/tax'
      path: '/solutions/tax'
      fullPath: '/solutions/tax'
      preLoaderRoute: typeof SolutionsTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/wealth-management': {
      id: '/solutions/wealth-management'
      path: '/solutions/wealth-management'
      fullPath: '/solutions/wealth-management'
      preLoaderRoute: typeof SolutionsWealthManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AutomotiveRoute: AutomotiveRoute,
  BookanappointmentRoute: BookanappointmentRoute,
  CareersRoute: CareersRoute,
  ConstructionRoute: ConstructionRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  FloridaLocationRoute: FloridaLocationRoute,
  HealthcareRoute: HealthcareRoute,
  HospitalityRoute: HospitalityRoute,
  IndustriesRoute: IndustriesRoute,
  IslandiaLocationRoute: IslandiaLocationRoute,
  LegalProfessionalsRoute: LegalProfessionalsRoute,
  ManufacturersRoute: ManufacturersRoute,
  NewYorkCityLocationRoute: NewYorkCityLocationRoute,
  OurTeamRoute: OurTeamRoute,
  PrivacyPolicy2Route: PrivacyPolicy2Route,
  RealEstateRoute: RealEstateRoute,
  ResourcesRoute: ResourcesRoute,
  RetailRoute: RetailRoute,
  TestimonialsRoute: TestimonialsRoute,
  TierraVerdeFlRoute: TierraVerdeFlRoute,
  BlogSlugRoute: BlogSlugRoute,
  SolutionsBookkeepingRoute: SolutionsBookkeepingRoute,
  SolutionsCfoAdvisoryServicesRoute: SolutionsCfoAdvisoryServicesRoute,
  SolutionsTaxRoute: SolutionsTaxRoute,
  SolutionsWealthManagementRoute: SolutionsWealthManagementRoute,
  BlogIndexRoute: BlogIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
